model:
    arch: fcalexnet
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: ../datasets/VOCdevkit/VOC2011
training:
    epochs: 3
    batch_size: 1
    n_workers: 16
    print_interval: 5 # 5 iterations
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 1.6e-3 # or 0.0625
        momentum: 0.9
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: #runs/config/80202/fcn8s_pascal.pkl
