model:
    arch: fcalexnet
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: ../datasets/VOCdevkit/VOC2011
training:
    epochs: 500
    batch_size: 1
    acc_batch_size: 20
    n_workers: 4
    print_interval: 5 # in iterations
    optimizer:
        name: 'adam'
        lr: 1.0e-4
        weight_decay: 1.0e-3
    loss:
        name: 'micro_average'
    lr_schedule:
    resume: #runs/config/80202/fcn8s_pascal.pkl
