model:
    arch: fcnan
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: ../VOCdevkit/VOC2011
training:
    train_iters: 300000
    batch_size: 1
    val_interval: 1000
    n_workers: 0
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 1.6e-3 # or 0.0625
        momentum: 0.9
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: #runs/config/80202/fcn8s_pascal.pkl
