model:
    arch: fcalexnet
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: ../datasets/VOCdevkit/VOC2011
training:
    epochs: 500
    batch_size: 1
    acc_batch_size: 20
    n_workers: 1
    print_interval: 5 # in iterations
    optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 0
    loss:
        name: 'macro_average'
    lr_schedule:
    resume: runs/alexnet_mi_adam_4_4/mi adam lr=1e-4 wd=1e-4/fcalexnet_pascal_best_model.pkl
