model:
    arch: fcn32s
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 256
    img_cols: 256
    path: ../VOCdevkit/VOC2012
training:
    train_iters: 300000
    batch_size: 12
    val_interval: 1000
    n_workers: 0
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-4
        weight_decay: 1.6e-3 # or 0.0625
        momentum: 0.9
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: #runs/config/80202/fcn8s_pascal.pkl
